triggers:
  - type: page_open
    when: (@ not thread.open_page )

steps:
  - say: Hey, welcome!
  - thread_set:
      open_page: true
  - user_set:
      page_user_id: (@ flow.event.data.context.user_id )
